language: node_js
node_js:
  - "12.16.1"

cache: yarn

matrix:
  include:
    - name: "Server Pipeline"
      env: TARGET=packages/simple-script-server APP_NAME=simple-script

services:
  - mongodb
script:
  - cd $TARGET
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  skip_cleanup: true
  app: $APP_NAME
  on:
    tags: true
