language: node_js
node_js:
  - "12.16.1"

cache: yarn

matrix:
  include:
    - name: "Server Pipeline"
      env: TARGET=packages/simple-script-server

script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "$TARGET is being built" && cd $TARGET && yarn lint && yarn test && yarn build; else echo "$TARGET is NOT being built"; fi
